apiVersion: v1
kind: Service
metadata:
  name: olha-api-app-loadbalancer-service
  namespace: olha-namespace
  labels:
    app: olha-api-app
spec:
  selector:
    app: olha-api-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80