apiVersion: apps/v1
kind: Deployment
metadata:
  name: olha-ui-app-deploy
  namespace: olha-namespace
  labels:
    app: olha-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: olha-ui-app
  template:
    metadata:
      name: olha-ui-app
      labels:
        app: olha-ui-app
    spec:
      volumes:
        - name: config
          configMap:
            name: ui-configmap
            items:
              - key: config.json
                path: config.json
      containers:
        - name: olha-ui-app
          image: kholha/ui-app:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: "/usr/share/nginx/html/configs/"
              readOnly: true