apiVersion: v1
kind: Service
metadata:
  name:  basic-3tier-postgres
  namespace: olha-namespace
  labels:
    app:  basic-3tier-postgres
spec:
  type: ClusterIP
  selector:
    app:  basic-3tier-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
