name: Deploy to EKS

on:
  push:
    branches: [ "docker-deployment" ]
  pull_request:
    branches: [ "docker-deployment" ]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build UI image and push to DockerHub
      - name: Build and push UI
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ./ui/Dockerfile
          push: true
          tags: |
            kholha/ui-app:latest
            kholha/ui-app:1.0.0

      # Build API image WITHOUT CACHE and push to DockerHub
#      - name: Build and push API
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          context: "{{defaultContext}}:api"
#          push: true
#          tags: |
#            kholha/api-app:latest
#            kholha/api-app:1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run Ansible playbook
        run: ansible-playbook ./ansible/install_docker.yml -i ./ansible/hosts.yml

      - name: Pull images from DockerHub
        run: |
          docker pull postgres:latest
          docker pull kholha/api-app:latest
          docker pull kholha/ui-app:latest

      - name: Run containers
        run: |
          docker up -d postgres:latest
          docker up -d kholha/api-app:latest
          docker up -d kholha/ui-app:latest