name: Push Frontend and Backend image to Docker HUb

on:
  push:
    branches:
      - 'master'

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{secrets.SSH_HOST}}
  USER_NAME: ${{secrets.USER_NAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              rm -rf 3_tier_build_private_repo &&
              git clone https://github.com/KhOlga/3_tier_build_private_repo.git &&
              cd 3_tier_build_private_repo &&
              git checkout docker-compose-deployment &&
              sudo docker compose up -d
              '