name: Deploy application

on:
  push:
    branches:
      - 'master'

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{secrets.SSH_HOST}}
  USER_NAME: ${{secrets.USER_NAME}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: actions/checkout@v4

      - name: Deploy application and run docker containers
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              
              sudo rm -rf 3_tier_build_private_repo &&
              git clone https://github.com/KhOlga/3_tier_build_private_repo.git &&
              cd 3_tier_build_private_repo &&
              sudo docker compose up -d &&
              cd ../ &&
              sudo rm -rf loki/ &&
              sudo mkdir loki &&
              cd loki
              sudo wget https://raw.githubusercontent.com/grafana/loki/v3.0.0/cmd/loki/loki-local-config.yaml -O loki-config.yaml &&
              sudo wget https://raw.githubusercontent.com/grafana/loki/v3.0.0/clients/cmd/promtail/promtail-docker-config.yaml -O promtail-config.yaml &&
              sudo docker run --name loki -d -v $(pwd):/mnt/config -p 3100:3100 grafana/loki:3.0.0 -config.file=/mnt/config/loki-config.yaml &&
              sudo docker run --name promtail -d -v $(pwd):/mnt/config -v /var/log:/var/log --link loki grafana/promtail:3.0.0 -config.file=/mnt/config/promtail-config.yaml
              '